name: Manual Trigger Example

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod
      message:
        description: "Custom message"
        required: false
        default: "Triggered manually!"

jobs:
  run-manual-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print input values
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Message: ${{ github.event.inputs.message }}"

      - name: Do some action
        run: echo "This job was triggered manually!"
