name: My test workflow

on:
  pull_request:
    types: [opened, reopened]

jobs:
    initial_job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome banner
          run: echo "Hello there"
        
        - name: list repo files
          run: ls -l
