name: With Cache Example

on:
  pull_request:
    types: [opened, reopened]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Txt file
        run: |
          mkdir -p output
          echo "Generated on $(date)" > output/output.txt
          cat output/output.txt

      - name: Save to cache
        uses: actions/cache@v4
        with:
          path: output
          key: output-cache

  reuse_using_cache:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: output
          key: output-cache

      - name: Read cached file
        run: |
          if [ -f output/output.txt ]; then
            echo "Found cached file:"
            cat output/output.txt
          else
            echo "No cached file found."
          fi
